/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ICEAGE.java
 *
 * Created on 15 Apr, 2017, 10:03:57 PM
 */

package frames;

import frames.movies;
import frames.species;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author MockingJay
 */
public class ZOOTOPIA extends javax.swing.JFrame {

    /** Creates new form ICEAGE */
    public ZOOTOPIA() {
        initComponents();
    }

     public void method1(String fandom,String h,int q,String g,String size,int price,int tot)
    { int f=0;
      try{
   Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/ipproject","root","candy123");
Statement stmt=conn.createStatement();
 String qwe="select item,size from cart ;";
 ResultSet rs=stmt.executeQuery(qwe);
 while(rs.next()){
 String hey=rs.getString("item");
 String siz=rs.getString("size");
if((g.equals(hey))&&(size.equals(siz)))
f++;}}
 catch(Exception e)
 {}
      if(f!=0)
          {try
 {
Connection cw=DriverManager.getConnection("jdbc:mysql://localhost:3306/ipproject","root","candy123");
Statement set=cw.createStatement();
        String qw="update cart set quantity=quantity+"+q+" where item_no=\""+h+"\";";
         String qwer="update cart set total=rate*quantity;";
        set.executeUpdate(qw);
        set.executeUpdate(qwer);
 JOptionPane.showMessageDialog(null,"Quantity sucessfully changed");
 }
catch(Exception e){JOptionPane.showMessageDialog(null, "Technical Errors");}
}
else{
     try
 {
 Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/ipproject","root","candy123");
Statement stm=con.createStatement();
 String qwe="select * from products where product_code=\""+h+"\";";
 ResultSet rd=stm.executeQuery(qwe);
 while(rd.next()){
 fandom=rd.getString("fandoms");
price=rd.getInt("price");
 h=rd.getString("product_Code");
 tot=price*q;}
 }
catch(Exception e){JOptionPane.showMessageDialog(null,"error in connectivity");}
try{
    Connection cone=DriverManager.getConnection("jdbc:mysql://localhost:3306/ipproject","root","candy123");
  Statement stamt=cone.createStatement();
String qwer="insert into cart values(\""+fandom+"\",\""+h+"\",\""+g+"\","+q+",\""+size+"\","+price+","+tot+");";
stamt.executeUpdate(qwer);
JOptionPane.showMessageDialog(null, "Your Item has been Successfully Added to Your Cart.");
}
catch(Exception e)
{JOptionPane.showMessageDialog(null,"Error in connectivity");}}}



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        n1 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        n2 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cb2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        n4 = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        n5 = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        n3 = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        q1 = new javax.swing.JTextField();
        q2 = new javax.swing.JTextField();
        q3 = new javax.swing.JTextField();
        q4 = new javax.swing.JTextField();
        q5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBounds(new java.awt.Rectangle(150, 0, 850, 800));
        setMinimumSize(new java.awt.Dimension(850, 720));
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Zootopia JPosters.com.ar", 0, 24)); // NOI18N
        jButton1.setText("ADD TO CART");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(450, 630, 270, 41);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fandom/zootopia shirt.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 20, 180, 180);

        n1.setFont(new java.awt.Font("Zootopia JPosters.com.ar", 0, 18)); // NOI18N
        n1.setText("ZOOTOPIA TSHIRT");
        n1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n1ActionPerformed(evt);
            }
        });
        getContentPane().add(n1);
        n1.setBounds(20, 210, 191, 33);

        jLabel6.setFont(new java.awt.Font("Zootopia JPosters.com.ar", 0, 14)); // NOI18N
        jLabel6.setText("QTY");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 250, 40, 19);

        jLabel7.setFont(new java.awt.Font("Zootopia JPosters.com.ar", 0, 14)); // NOI18N
        jLabel7.setText("SIZE");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(130, 250, 29, 19);

        cb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "XS", "S", "M", "L", "XL", "XXL" }));
        getContentPane().add(cb1);
        cb1.setBounds(180, 250, 50, 22);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fandom/zootopia slingbag.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(330, 30, 178, 170);

        n2.setFont(new java.awt.Font("Zootopia JPosters.com.ar", 0, 18)); // NOI18N
        n2.setText("ZOOTOPIA SL INGBAG");
        n2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n2ActionPerformed(evt);
            }
        });
        getContentPane().add(n2);
        n2.setBounds(300, 210, 221, 33);

        jLabel8.setFont(new java.awt.Font("Zootopia JPosters.com.ar", 0, 14)); // NOI18N
        jLabel8.setText("QTY");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(330, 250, 40, 19);

        jLabel9.setFont(new java.awt.Font("Zootopia JPosters.com.ar", 0, 14)); // NOI18N
        jLabel9.setText("SIZE");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(440, 250, 29, 19);

        cb2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "XS", "S", "M", "L", "XL", "XXL" }));
        getContentPane().add(cb2);
        cb2.setBounds(480, 250, 50, 22);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fandom/zootopiA BADGE.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 330, 186, 181);

        n4.setFont(new java.awt.Font("Zootopia JPosters.com.ar", 0, 18)); // NOI18N
        n4.setText("ZOOTOPIA BADGE");
        n4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n4ActionPerformed(evt);
            }
        });
        getContentPane().add(n4);
        n4.setBounds(150, 520, 187, 33);

        jLabel11.setFont(new java.awt.Font("Zootopia JPosters.com.ar", 0, 14)); // NOI18N
        jLabel11.setText("QTY");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(220, 560, 40, 19);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fandom/Z MUG.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(490, 330, 178, 187);

        n5.setFont(new java.awt.Font("Zootopia JPosters.com.ar", 0, 18)); // NOI18N
        n5.setText("ZOOTOPIA MUG");
        n5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n5ActionPerformed(evt);
            }
        });
        getContentPane().add(n5);
        n5.setBounds(480, 520, 167, 33);

        jLabel12.setFont(new java.awt.Font("Zootopia JPosters.com.ar", 0, 14)); // NOI18N
        jLabel12.setText("QTY");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(520, 560, 40, 19);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fandom/Z PH COVER.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(620, 30, 174, 170);

        n3.setFont(new java.awt.Font("Zootopia JPosters.com.ar", 0, 14)); // NOI18N
        n3.setText("ZOOTOPIA  PHONE COVER");
        n3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n3ActionPerformed(evt);
            }
        });
        getContentPane().add(n3);
        n3.setBounds(590, 210, 207, 27);

        jLabel13.setFont(new java.awt.Font("Zootopia JPosters.com.ar", 0, 14)); // NOI18N
        jLabel13.setText("QTY");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(650, 260, 40, 19);

        jButton2.setFont(new java.awt.Font("Zootopia JPosters.com.ar", 0, 24)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(110, 640, 270, 41);

        jLabel10.setText("PRICE:Rs 299");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(480, 590, 110, 16);

        jLabel14.setText("PRICE:Rs 449");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(30, 280, 110, 16);

        jLabel15.setText("PRICE:Rs 499");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(340, 280, 110, 16);

        jLabel16.setText("PRICE:Rs 99");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(610, 280, 100, 16);

        jLabel17.setText("PRICE:Rs 99");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(140, 590, 120, 16);
        getContentPane().add(q1);
        q1.setBounds(70, 250, 59, 22);
        getContentPane().add(q2);
        q2.setBounds(370, 250, 59, 22);
        getContentPane().add(q3);
        q3.setBounds(690, 260, 59, 22);
        getContentPane().add(q4);
        q4.setBounds(270, 560, 59, 22);
        getContentPane().add(q5);
        q5.setBounds(560, 560, 59, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void n1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_n1ActionPerformed

    private void n2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_n2ActionPerformed

    private void n4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n4ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_n4ActionPerformed

    private void n5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n5ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_n5ActionPerformed

    private void n3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n3ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_n3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if((n1.isSelected()==false)&&(n2.isSelected()==false)&&(n3.isSelected()==false)&&(n4.isSelected()==false)&&(n5.isSelected()==false))
{JOptionPane.showMessageDialog(null, "PLEASE SELECT ALTEAST 1 ITEM");}


 if(n1.isSelected()==true)
{String z=q1.getText();
 if(z.equals(""))
 {JOptionPane.showMessageDialog(null, "Please enter the Quantity.");
 }
 else{
 int a=Integer.parseInt(z);
  String size=(String) cb1.getSelectedItem()  ;
   String itnam=n1.getText();
   int tot=0,price=0;
   String fandom = null,procod = "ZO711";
  method1(fandom,procod,a,itnam,size,price,tot);}}




if(n2.isSelected()==true)
{String z=q2.getText();
 if(z.equals(""))
 {JOptionPane.showMessageDialog(null, "Please enter the Quantity.");
 }
 else{
 int a=Integer.parseInt(z);
  String size=(String) cb2.getSelectedItem()  ;
   String itnam=n2.getText();
   int tot=0,price=0;
   String fandom = null,procod = "ZO721";
  method1(fandom,procod,a,itnam,size,price,tot);}}



if(n3.isSelected()==true)
{String z=q3.getText();
 if(z.equals(""))
 {JOptionPane.showMessageDialog(null, "Please enter the Quantity.");
 }
 else{
 int a=Integer.parseInt(z);
  String size="null"  ;
   String itnam=n3.getText();
   int tot=0,price=0;
   String fandom = null,procod = "ZO741";
  method1(fandom,procod,a,itnam,size,price,tot);}}




   if(n4.isSelected()==true)
{String z=q4.getText();
 if(z.equals(""))
 {JOptionPane.showMessageDialog(null, "Please enter the Quantity.");
 }
 else{
 int a=Integer.parseInt(z);
  String size="null"  ;
   String itnam=n4.getText();
   int tot=0,price=0;
   String fandom = null,procod = "ZO731";
  method1(fandom,procod,a,itnam,size,price,tot);}}



   if(n5.isSelected()==true)
{String z=q5.getText();
 if(z.equals(""))
 {JOptionPane.showMessageDialog(null, "Please enter the Quantity.");
 }
 else{
 int a=Integer.parseInt(z);
  String size="null";
   String itnam=n5.getText();
   int tot=0,price=0;
   String fandom = null,procod = "ZO751";
  method1(fandom,procod,a,itnam,size,price,tot);}}


NewJFrame n=new NewJFrame();
n.setVisible(true);
     // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         movies n= new movies();
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ZOOTOPIA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb1;
    private javax.swing.JComboBox cb2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JCheckBox n1;
    private javax.swing.JCheckBox n2;
    private javax.swing.JCheckBox n3;
    private javax.swing.JCheckBox n4;
    private javax.swing.JCheckBox n5;
    private javax.swing.JTextField q1;
    private javax.swing.JTextField q2;
    private javax.swing.JTextField q3;
    private javax.swing.JTextField q4;
    private javax.swing.JTextField q5;
    // End of variables declaration//GEN-END:variables

}
